[package]
authors = ["jD91mZM2 <me@krake.one>"]
description = "xautolock rewrite in Rust, with a few extra features"
edition = "2018"
license = "MIT"
name = "xidlehook-daemon"
readme = "README.md"
repository = "https://github.com/jD91mZM2/xidlehook"
version = "0.8.0"
default-run = "xidlehook"

[dependencies]
env_logger = "0.7.0"
futures-preview = "=0.3.0-alpha.19"
log = "0.4.8"
nix = "0.15.0"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"
structopt = "0.3.2"
xcb = { version = "0.8.2", features = ["x11", "screensaver"] }
xidlehook = { path = "../xidlehook/", features = ["async-std"] }

# Requires async-std fork because of
# https://github.com/async-rs/async-std/issues/248
[dependencies.async-std]
git = "https://github.com/mvucenovic/async-std"
rev = "a057733606f7b32f06d57ad0e945e422cb7030c5"
features = [ "unstable" ]

[dependencies.libpulse-binding]
optional = true
version = "2.6.0"
default-features = false
features = ["pa_v12_compatibility"]

[features]
default = ["pulse"]
pulse = ["libpulse-binding"]

[[bin]]
# Rename binary of "xidlehook-daemon" to just "xidlehook"
name = "xidlehook"
path = "src/main.rs"
